language: node_js
sudo: required
dist: trusty
matrix:
  include:
    - node_js: "0.10"
      script: "npm test"
    - node_js: "0.12"
      script: "npm test"
    - node_js: "4"
      script: "npm test"
    - node_js: "6"
      script: "npm run travis"
addons:
  postgresql: "9.5"
before_script:
  - psql -c 'create database pg_promise_test;' -U postgres
  - node test/db/init.js
env:
  - BLUEBIRD_DEBUG=0
